### ISSUE TITLE
Label Highlight and Save Issues

### ISSUE THREAD

**Issue by tlint101** [cbouy/molhighlighter#1]
Hello! This is a nice and easy to use package. Thanks!

I had a minor question. Is there a way to create the molecule image and label without having the label highlighted? For example, my code here:

```python
name_list = ['Tryptamine', 'Serotonin']
mol_list = ['c1ccc2c(c1)c(c[nH]2)CCN', 'C1=CC2=C(C=C1O)C(=CN2)CCN']

query = Chem.MolFromSmiles('N1C=CC2=C1C=CC=C2')
query_struct = Chem.MolToSmarts(query)

for (molecule, names) in zip(mol_list, name_list):
    mol = Chem.MolFromSmiles(molecule)
    highlight = [mh.Smarts(mol, query_struct, color='#89c7a8', text=names, fill_ring=False)]
    molh = mh.MolHighlighter(mol, highlight, label=names)
    molh.display()
```

I get the molecule highlighted the way I was expecting, but I am unsure of how to have the label shown without the highlights. 

I also do not get prompts when I use:

```python
molh.save()
```

In JupyterNotebook, it is fine and will display the figure and highlights. However, the molh.save() does not save the image. Instead I get:

```
../site-packages/molhighlighter/molhighlighter.py:292: UserWarning: Path provided but not used for saving
  warnings.warn("Path provided but not used for saving")
```

**Comment by cbouy** [comment]
Adding a label without highlighting it (i.e. simply using the molecule drawing code) is not really the use case that I had in mind, but I guess you could modify the `MolHighlighter` class for that matter:

```python
class MyMolHighlighter(mh.MolHighlighter):
    def _get_span_element(self, text, color):
        return f'<span>{text}</span>'
```
and then just use that class instead of `mh.MolHighlighter`

For the problem with `molh.save()`, I guess it's either from using JupyterLab (I never tested that code for this platform which does a few things differently webbrowser-side), or there's been some recent changes in Jupyter notebooks that break the HTML-to-png JavaScript code used for generating the image, in which case try downgrading your notebook install to `pip install 'notebook<7'` (I think I was on v6.4 when I last updated this).
